# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import bidirectional_pb2 as bidirectional__pb2


class BidirectionalStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetServerResponse = channel.stream_stream(
        '/bidirectional.Bidirectional/GetServerResponse',
        request_serializer=bidirectional__pb2.Message.SerializeToString,
        response_deserializer=bidirectional__pb2.Message.FromString,
        )


class BidirectionalServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetServerResponse(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BidirectionalServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetServerResponse': grpc.stream_stream_rpc_method_handler(
          servicer.GetServerResponse,
          request_deserializer=bidirectional__pb2.Message.FromString,
          response_serializer=bidirectional__pb2.Message.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'bidirectional.Bidirectional', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
