# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from unary import unary_pb2 as unary_dot_unary__pb2


class UnaryStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetServerResponse = channel.unary_unary(
        '/unary.Unary/GetServerResponse',
        request_serializer=unary_dot_unary__pb2.Message.SerializeToString,
        response_deserializer=unary_dot_unary__pb2.MessageResponse.FromString,
        )


class UnaryServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetServerResponse(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UnaryServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetServerResponse': grpc.unary_unary_rpc_method_handler(
          servicer.GetServerResponse,
          request_deserializer=unary_dot_unary__pb2.Message.FromString,
          response_serializer=unary_dot_unary__pb2.MessageResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'unary.Unary', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
